# Site settings
title: stefan boicea's place on the interwebs
email: stefanboicea@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Expressing myself personally and professionally online.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://boicea.com" # the base hostname & protocol for your site

twitter_username: stefanboicea

# Build settings
markdown: kramdown
